#!/bin/sh
git clone https://github.com/4j4y/ruby_template.git
mv ruby_template $1
cd $1
mv bin/project_name bin/$1
mkdir lib/$1
mkdir spec/$1
mv lib/project_name.rb lib/$1".rb"
echo "require '$1'" >> spec/spec_helper.rb
rm -rf .git
git init
